CREATE DATABASE SoftUni
GO
USE SoftUni
GO

CREATE TABLE Towns (
	Id INT IDENTITY(1,1) NOT NULL, 
	Name NVARCHAR(20)
)
ALTER TABLE Towns
ADD CONSTRAINT PK_Towns PRIMARY KEY(Id)

CREATE TABLE Addresses (
	Id INT IDENTITY(1,1) NOT NULL, 
	AddressText NVARCHAR(50) NOT NULL, 
	TownId INT NOT NULL
)
ALTER TABLE Addresses
ADD CONSTRAINT PK_Addresses PRIMARY KEY(Id)
ALTER TABLE Addresses
ADD CONSTRAINT FK_Addresses_Towns FOREIGN KEY(TownId) REFERENCES Towns

CREATE TABLE Departments (
	Id INT IDENTITY(1,1) NOT NULL, 
	Name NVARCHAR(20) NOT NULL
)
ALTER TABLE Departments
ADD CONSTRAINT PK_Departments PRIMARY KEY(Id)

CREATE TABLE Employees (
	Id INT IDENTITY(1,1) NOT NULL, 
	FirstName NVARCHAR(20) NOT NULL, 
	MiddleName NVARCHAR(20) NOT NULL, 
	LastName NVARCHAR(20) NOT NULL, 
	JobTitle NVARCHAR(20) NOT NULL, 
	DepartmentId INT NOT NULL,
	HireDate DATE NOT NULL, 
	Salary MONEY NOT NULL, 
	AddressId INT NOT NULL
)

ALTER TABLE Employees
ADD CONSTRAINT PK_Employees PRIMARY KEY(Id)
ALTER TABLE Employees
ADD CONSTRAINT FK_Employees_Departments FOREIGN KEY(DepartmentId) REFERENCES Departments
ALTER TABLE Employees
ADD CONSTRAINT FK_Employees_Addresses FOREIGN KEY(AddressId) REFERENCES Addresses