# Generated by Django 4.1.4 on 2022-12-19 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(null=True)),
                ('department_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
    ]
