// Generated by https://quicktype.io
package docs

type SDP struct {
	Request        Request        `json:"request"`
	ResponseStatus ResponseStatus `json:"response_status"`
}

type Request struct {
	OlaDueByTime                 interface{}   `json:"ola_due_by_time"`
	Subject                      string        `json:"subject"`
	ServiceSla                   interface{}   `json:"service_sla"`
	Resolution                   Resolution    `json:"resolution"`
	LinkedToRequest              interface{}   `json:"linked_to_request"`
	OnholdTime                   interface{}   `json:"onhold_time"`
	Mode                         Category      `json:"mode"`
	IsRead                       bool          `json:"is_read"`
	HasPurchaseRequests          bool          `json:"has_purchase_requests"`
	Lifecycle                    Category      `json:"lifecycle"`
	ReasonForCancel              interface{}   `json:"reason_for_cancel"`
	Assets                       []interface{} `json:"assets"`
	IsTrashed                    bool          `json:"is_trashed"`
	ID                           string        `json:"id"`
	AssignedTime                 interface{}   `json:"assigned_time"`
	Group                        GroupClass    `json:"group"`
	Requester                    CreatedBy     `json:"requester"`
	CancelRequestedBy            interface{}   `json:"cancel_requested_by"`
	EmailTo                      []interface{} `json:"email_to"`
	SlaViolatedTechnician        interface{}   `json:"sla_violated_technician"`
	CreatedTime                  CompletedTime `json:"created_time"`
	HasResolutionAttachments     bool          `json:"has_resolution_attachments"`
	ApprovalStatus               interface{}   `json:"approval_status"`
	ServiceCategory              Category      `json:"service_category"`
	Sla                          interface{}   `json:"sla"`
	ResolvedTime                 CompletedTime `json:"resolved_time"`
	Priority                     Priority      `json:"priority"`
	CreatedBy                    CreatedBy     `json:"created_by"`
	SlaViolatedGroup             interface{}   `json:"sla_violated_group"`
	ScheduledEndTime             interface{}   `json:"scheduled_end_time"`
	Tags                         []interface{} `json:"tags"`
	FirstResponseDueByTime       interface{}   `json:"first_response_due_by_time"`
	LastUpdatedTime              CompletedTime `json:"last_updated_time"`
	HasNotes                     bool          `json:"has_notes"`
	UdfFields                    UdfFields     `json:"udf_fields"`
	Subcategory                  Category      `json:"subcategory"`
	EmailCc                      []interface{} `json:"email_cc"`
	Status                       Priority      `json:"status"`
	ScheduledStartTime           interface{}   `json:"scheduled_start_time"`
	Template                     Template      `json:"template"`
	PrimaryAsset                 interface{}   `json:"primary_asset"`
	RequestType                  Category      `json:"request_type"`
	TimeElapsed                  CompletedTime `json:"time_elapsed"`
	CancelRequestedTime          interface{}   `json:"cancel_requested_time"`
	NotificationStatus           interface{}   `json:"notification_status"`
	HasPurchaseOrders            bool          `json:"has_purchase_orders"`
	Description                  string        `json:"description"`
	HasDependency                bool          `json:"has_dependency"`
	AgeAfterViolation            interface{}   `json:"age_after_violation"`
	ClosureInfo                  ClosureInfo   `json:"closure_info"`
	HasConversation              bool          `json:"has_conversation"`
	CallbackURL                  interface{}   `json:"callback_url"`
	ChatType                     int64         `json:"chat_type"`
	IsServiceRequest             bool          `json:"is_service_request"`
	IsShared                     bool          `json:"is_shared"`
	CancelRequested              bool          `json:"cancel_requested"`
	HasRequestInitiatedChange    bool          `json:"has_request_initiated_change"`
	RequestTemplateTaskIDS       []interface{} `json:"request_template_task_ids"`
	Department                   GroupClass    `json:"department"`
	IsReopened                   bool          `json:"is_reopened"`
	HasDraft                     bool          `json:"has_draft"`
	HasAttachments               bool          `json:"has_attachments"`
	HasLinkedRequests            bool          `json:"has_linked_requests"`
	Resources                    Resources     `json:"resources"`
	IsOverdue                    bool          `json:"is_overdue"`
	Technician                   interface{}   `json:"technician"`
	HasRequestCausedByChange     bool          `json:"has_request_caused_by_change"`
	DueByTime                    interface{}   `json:"due_by_time"`
	IsFcr                        bool          `json:"is_fcr"`
	TotalUnassignedTime          CompletedTime `json:"total_unassigned_time"`
	Site                         Category      `json:"site"`
	AgeAfterSlaResponseViolation interface{}   `json:"age_after_sla_response_violation"`
	IsFirstResponseOverdue       bool          `json:"is_first_response_overdue"`
	CompletedTime                CompletedTime `json:"completed_time"`
	CancelRequestedIsPending     bool          `json:"cancel_requested_is_pending"`
	RecommendTemplate            interface{}   `json:"recommend_template"`
	UnrepliedCount               interface{}   `json:"unreplied_count"`
	Category                     Category      `json:"category"`
}

type Category struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type ClosureInfo struct {
	RequesterACKComments   interface{} `json:"requester_ack_comments"`
	ClosureCode            interface{} `json:"closure_code"`
	ClosureComments        interface{} `json:"closure_comments"`
	RequesterACKResolution bool        `json:"requester_ack_resolution"`
}

type CompletedTime struct {
	DisplayValue string `json:"display_value"`
	Value        string `json:"value"`
}

type CreatedBy struct {
	EmailID    *string              `json:"email_id"`
	Phone      interface{}          `json:"phone"`
	Name       string               `json:"name"`
	Mobile     *string              `json:"mobile"`
	ProfilePic ProfilePic           `json:"profile_pic"`
	IsVipuser  bool                 `json:"is_vipuser"`
	ID         string               `json:"id"`
	Department *CreatedByDepartment `json:"department"`
}

type CreatedByDepartment struct {
	Site Site   `json:"site"`
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

type Site struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

type ProfilePic struct {
	ContentURL string `json:"content-url"`
	Name       string `json:"name"`
}

type GroupClass struct {
	Site *ServiceCategory `json:"site"`
	Name string           `json:"name"`
	ID   string           `json:"id"`
}

type ServiceCategory struct {
	ID string `json:"id"`
}

type Priority struct {
	Color *string `json:"color"`
	Name  string  `json:"name"`
	ID    string  `json:"id"`
}

type Resolution struct {
	ResolutionAttachments []interface{} `json:"resolution_attachments"`
	Content               interface{}   `json:"content"`
}

type Resources struct {
	Res301 map[string]*Res301 `json:"res_301"`
	Res302 Res302             `json:"res_302"`
}

type Res301 struct {
	Value interface{} `json:"value"`
}

type Res302 struct {
	QstnSelect1 interface{} `json:"qstn_select_1"`
}

type Template struct {
	IsServiceTemplate bool            `json:"is_service_template"`
	ServiceCategory   ServiceCategory `json:"service_category"`
	Name              string          `json:"name"`
	ID                string          `json:"id"`
}

type UdfFields struct {
	UdfPick901  string      `json:"udf_pick_901"`
	UdfPick902  string      `json:"udf_pick_902"`
	UdfSline605 string      `json:"udf_sline_605"`
	UdfSline903 string      `json:"udf_sline_903"`
	UdfPick637  interface{} `json:"udf_pick_637"`
	UdfPick638  interface{} `json:"udf_pick_638"`
	UdfPick639  string      `json:"udf_pick_639"`
}

type ResponseStatus struct {
	StatusCode int64  `json:"status_code"`
	Status     string `json:"status"`
}
