package dao

// form move tu SDP => jira 1
const KTemplate1 = "304"

// SDP	|Jira
// Request Type |	Type
// Status	| Status
// Technician	| Assignee
// Mode	| Nguồn yêu cầu
// Thông tin liên hệ	| Thông tin liên hệ
// Số điện thoại	| Số điện thoại
// Subcategory	| Phân loại chi tiết yêu cầu
// Component	| Component/S
// Chức năng cấp 1 ghép với chức năng cấp 2 (Cấp 1- Cấp 2)|	Phân hệ CMIS 3.0
// Đơn vị khách hàng cấp 1 ghép với đơn vị khách hàng cấp 2 (Cấp 1 - Cấp 2)	|Đơn vị/Khách hàng
// Create date|	Created
// Generated by https://quicktype.io

type Template1 struct {
	Request Request `json:"request"`
}

type Request struct {
	Subject                   string      `json:"subject"`
	Mode                      SelectVal   `json:"mode"`
	ID                        string      `json:"id"`
	CreatedTime               CreatedTime `json:"created_time"`
	ServiceCategory           SelectVal   `json:"service_category"`
	Priority                  Priority    `json:"priority"`
	HasNotes                  bool        `json:"has_notes"`
	UdfFields                 UdfFields   `json:"udf_fields"`
	Subcategory               SelectVal   `json:"subcategory"` // Chức năng cấp 1 - Phân hệ CMIS 3.0
	Item                      SelectVal   `json:"item"`        // Chức năng cấp 2 - Phân hệ CMIS 3.0
	Status                    Priority    `json:"status"`
	Template                  Templatex1  `json:"template"`
	RequestType               SelectVal   `json:"request_type"`
	HasPurchaseOrders         bool        `json:"has_purchase_orders"`
	Description               string      `json:"description"`
	HasDependency             bool        `json:"has_dependency"`
	HasConversation           bool        `json:"has_conversation"`
	ChatType                  int64       `json:"chat_type"`
	IsServiceRequest          bool        `json:"is_service_request"`
	IsShared                  bool        `json:"is_shared"`
	CancelRequested           bool        `json:"cancel_requested"`
	HasRequestInitiatedChange bool        `json:"has_request_initiated_change"`
	IsReopened                bool        `json:"is_reopened"`
	HasDraft                  bool        `json:"has_draft"`
	HasAttachments            bool        `json:"has_attachments"`
	HasLinkedRequests         bool        `json:"has_linked_requests"`
	Resources                 Resources   `json:"resources"`
	IsOverdue                 bool        `json:"is_overdue"`
	HasRequestCausedByChange  bool        `json:"has_request_caused_by_change"`
	IsFirstResponseOverdue    bool        `json:"is_first_response_overdue"`
	CancelRequestedIsPending  bool        `json:"cancel_requested_is_pending"`
	Category                  SelectVal   `json:"category"`
	//	Group                     GroupClass  `json:"group"` // deprecated
}

type SelectVal struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type CreatedTime struct {
	DisplayValue string `json:"display_value"`
	Value        string `json:"value"`
}

type GroupClass struct {
	Site *ServiceCategory1 `json:"site"`
	Name string            `json:"name"`
	ID   string            `json:"id"`
}

type ServiceCategory struct {
	ID string `json:"id"`
}

type ServiceCategory1 struct {
	ID int `json:"id"`
}

type Priority struct {
	Color *string `json:"color"`
	Name  string  `json:"name"`
	ID    string  `json:"id"`
}

type Resources struct {
	Res301 map[string]*Res301 `json:"res_301"`
	Res302 Res302             `json:"res_302"`
}

type Welcome struct {
	Res301 Res301 `json:"res_301"`
	Res302 Res302 `json:"res_302"`
}

type Res301 struct {
	QstnText305   QstnText   `json:"qstn_text_305"`
	QstnSelect5   QstnSelect `json:"qstn_select_5"`
	QstnSelect303 QstnSelect `json:"qstn_select_303"`
	QstnSelect304 QstnSelect `json:"qstn_select_304"`
	QstnSelect302 QstnSelect `json:"qstn_select_302"`
	QstnSelect1   QstnSelect `json:"qstn_select_1"`
	QstnText301   QstnText   `json:"qstn_text_301"`
	QstnSelect2   QstnSelect `json:"qstn_select_2"`
}

type Res302 struct {
	QstnSelect1 QstnSelect `json:"qstn_select_1"`
}

type QstnSelect struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type QstnText struct {
	Value string `json:"value"`
}

type Templatex1 struct {
	IsServiceTemplate bool `json:"is_service_template"`
	//ServiceCategory   ServiceCategory `json:"service_category"`
	Name string `json:"name"`
	ID   string `json:"id"`
}

type UdfFields struct {
	UdfPick2704  string `json:"udf_pick_2704"`  // Phân loại chi tiết yêu cầu
	UdfPick2706  string `json:"udf_pick_2706"`  // Đơn vị/Khách hàng 1
	UdfPick2707  string `json:"udf_pick_2707"`  // Đơn vị/Khách hàng 2
	UdfSline2708 string `json:"udf_sline_2708"` // Thông tin liên hệ
	UdfSline2709 string `json:"udf_sline_2709"` // Số điện thoại
	UdfPick2710  string `json:"udf_sline_2710"` // Link Jira
	UdfPick2712  string `json:"udf_pick_2712"`  // Trạng thái theo 5249
	UdfPick2713  string `json:"udf_pick_2713"`  // Giai Đoạn phát sinh
	UdfPick2714  string `json:"udf_pick_2714"`  // Issue trùng lặp
	UdfPick4203  string `json:"udf_pick_4203"`  // Mức độ gấp
	UdfPick3906  string `json:"udf_pick_3906"`  // Đơn vị chủ quản

	UdfPick3001 string `json:"udf_pick_3001"` //Component CMIS
	UdfPick3002 string `json:"udf_pick_3002"` //Component DOFFICE
	UdfPick3003 string `json:"udf_pick_3003"` //Component DTXDCB
	UdfPick3004 string `json:"udf_pick_3004"` //Component ERP
	UdfPick3005 string `json:"udf_pick_3005"` //Component PMIS
	UdfPick3006 string `json:"udf_pick_3006"` //Component EVNHES
	UdfPick3007 string `json:"udf_pick_3007"` //Component EAM
	UdfPick3008 string `json:"udf_pick_3008"` //Component MDMS
	UdfPick3009 string `json:"udf_pick_3009"` //Component EVNPORTAL
}
